application:
  order_address: http://localhost:8182/orders

spring:
  application:
    name: catalog-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

server:
  port: 8181