application:
  order-address: http://order-service:8182/orders

logging:
  level:
    it.polito.ap.catalogservice: DEBUG

server:
  port: 8181

spring:
  application:
    name: catalog-service
  cache:
    cache-names: "product"
    caffeine:
      spec: expireAfterWrite=300s
    type: caffeine
  data:
    mongodb:
      uri: mongodb://mongo:27017/CatalogDB
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      auto-offset-reset: earliest