application:
  warehouse-address: http://localhost:8084/warehouses
  wallet-address: http://localhost:8083/wallets
  consistency-check-timeout-ms: 30000

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

server:
  port: 8089