application:
  warehouse_address: http://localhost:8084/warehouses
  wallet_address: http://localhost:8083/wallets

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

server:
  port: 8089